version: '3'
services:

  db-lservices:
    image: mysql:5.7.25
    container_name: db-lservices
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=lservices
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql/
      - .docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      lservices_network:

  app-lservices:
    build: .docker/php-fpm
    image: app-laravel:0.1.0
    container_name: app-lservices
    depends_on:
      - db-lservices
    volumes:
      - ./:/var/www
      - .php-fpm/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      lservices_network:

  web-lservices:
    image: nginx:1.14.2-alpine
    container_name: web-lservices
    ports:
      - "8080:8080"
    depends_on:
      - app-lservices
    volumes:
      - ./:/var/www/
      - .docker/nginx/:/etc/nginx/
    networks:
      lservices_network:

#Volumes
volumes:
  db_data:
    driver: local

#Docker Networks
networks:
  lservices_network:
    driver: bridge